export const skippedIngredients = [
  'almond',
  'almonds',
  'baking powder',
  'baking soda',
  'carrot',
  'carrots',
  'cinnamon',
  'cocoa',
  'coffee',
  'cardamom',
  'cornstarch',
  'corn starch',
  'corn syrup',
  'cumin',
  'espresso',
  'extract',
  'flour',
  'garam',
  'garlic',
  'gelatin',
  'honey',
  'lemon',
  'milk',
  'nutmeg',
  'oil',
  'onion',
  'pepper',
  'peppers',
  'rum',
  'salt',
  'soy',
  'sugar',
  'tomato',
  'tomatoes',
  'turmeric',
  'vanilla',
  'walnut',
  'walnuts',
  'water',
  'yogurt'
]

export const transformedIngredients = {
  'beaten egg': 'egg',
  'beaten eggs': 'eggs',
  'chocolate coins': 'chocolate',
  'egg white': 'egg',
  'egg whites': 'eggs',
  'egg yolk': 'egg',
  'egg yolks': 'eggs',
  'raspberry puree': 'raspberries'
}
